import edu.ucdavis.jr.JR;

public class main
{
    static op void p(int) throws java.io.EOFException;
    static op void p2(int) throws java.io.EOFException;

    static process run
    {
	  while(true)
	  {
	    inni void p(int i) throws java.io.EOFException
	    {
		throw new java.io.EOFException();
	    }
	    [] void p2(int i) throws java.io.EOFException
	    {
		    if (i < 0)
			reply handler new Handler();
		throw new java.io.EOFException();
	    }
	  }
    }


    public static void main(String [] args)
    {
	    send p(3) handler new Handler();
	    try
	    {
		call p2(4);
	    }
	    catch (java.io.EOFException e)
	    {
		System.out.println("Caught through call to p2 with try/catch");
	    }
	    try
	    {
		call p(4);
	    }
	    catch (java.io.EOFException e)
	    {
		System.out.println("Caught through call to p with try/catch");
	    }
	    // oops, might exit before handler done.
	    // JR.exit(0);
    }
}

class Handler implements edu.ucdavis.jr.Handler
{
    public handler void method(java.io.EOFException e)
    {
	System.out.println("Caught java.io.EOFException " +
				"through handler object");
    }
}

