public class main
{
    static op int p(int) throws java.io.EOFException;
    static int p(int i) throws java.io.EOFException
    {
	throw new java.io.EOFException("from method p");
    }
    static op int p2(int) throws java.io.EOFException;
    static int p2(int i) throws java.io.EOFException
    {
	    forward p(3) handler new Handler2();
	    forward p(88) handler new Handler3();
	throw new java.io.EOFException("from method p2");
    }

    public static void main(String [] args)
    {
	    send p2(3) handler new Handler();
	    try
	    {
	        int hohoho;
		hohoho = p2(4);
		System.out.println("Ho Ho Ho " + hohoho);
	    }
	    catch (java.io.EOFException e)
	    {
		System.out.println("Caught through call to p2 with try/catch: " + e.toString());
	    }
    }
}

class Handler implements edu.ucdavis.jr.Handler
{
    public handler void method(java.io.EOFException e)
    {
	System.out.println("Caught java.io.EOFException " +
				"through Handler object: " + e.toString());
    }
}

class Handler2 implements edu.ucdavis.jr.Handler
{
    public handler void method(java.io.EOFException e)
    {
	System.out.println("Caught java.io.EOFException " +
				"through Handler2 object: " + e.toString());
    }
}

class Handler3 implements edu.ucdavis.jr.Handler
{
    public handler void method(java.io.EOFException e)
    {
	System.out.println("Caught java.io.EOFException " +
				"through Handler3 object: " + e.toString());
    }
}

