public class main
{
    static op int p2(int) throws java.io.EOFException;

    static process run
    {
        cap int (int) throws java.io.EOFException p2cap = p2;
	  while(true)
	  {
	    inni int p2cap(int i) throws java.io.EOFException
	    {
		    reply 1234 handler new Handler2();
		throw new java.io.EOFException();
	    }
	  }
    }


    public static void main(String [] args)
    {
        cap int (int) throws java.io.EOFException p2cap = p2;
	    send p2cap(3) handler new Handler();
	    try
	    {
		int hohoho = p2cap(4);
		System.out.println("Ho Ho Ho " + hohoho);

	    }
	    catch (java.io.EOFException e)
	    {
		System.out.println("Caught through call to p2 with try/catch");
	    }
    }
}

class Handler implements edu.ucdavis.jr.Handler
{
    public handler void method(java.io.EOFException e)
    {
	System.out.println("Caught java.io.EOFException " +
				"through handler object");
    }
}

class Handler2 implements edu.ucdavis.jr.Handler
{
    public handler void method(java.io.EOFException e)
    {
	System.out.println("Caught java.io.EOFException " +
				"through Handler2 object");
    }
}

