import edu.ucdavis.jr.JR;

// test of mixed type of exceptions

public class main {

    public static void main(String [] args) {
    	try	{
	co GO(1) {
		try	{
			System.out.println("ppc1");
			throw new java.io.EOFException();
		} catch (Exception e) {
			System.out.println("catch block in ppc1");
		}
	}
	[] GO(2) {
		System.out.println("ppc2");
		throw new NullPointerException();
	}
	[] GO(3);
	[] GO(4);
	} catch (Exception e) {
		System.out.println("catch block of co");
	}
	System.out.println("After co");
		
    }

    private static op String GO(int n);

    private static process MYPROCESS	{
	int n = 1;
	while(true)	{
		inni String GO(int x) st x == n { // service in order: deter.
			System.out.println("received GO: " + x);
			reply "HI";
			n++;
		}
	}
    }

}
